# Generated by Django 5.2 on 2025-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GisCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Компания')),
                ('average_rating', models.TextField(blank=True, null=True, verbose_name='Средний рейтинг')),
                ('reviews_count', models.TextField(blank=True, null=True, verbose_name='Кол-во отзывов')),
            ],
        ),
        migrations.CreateModel(
            name='GisInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(verbose_name='Компания')),
                ('organization_id', models.TextField(verbose_name='id организации')),
            ],
        ),
        migrations.CreateModel(
            name='GisReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Компания')),
                ('rating', models.TextField(blank=True, null=True, verbose_name='Рейтинг')),
                ('created_at', models.TextField(blank=True, null=True, verbose_name='Дата')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('author_name', models.TextField(blank=True, null=True, verbose_name='Автор')),
                ('author_avatar_url', models.TextField(blank=True, null=True, verbose_name='Аватарка автора')),
                ('review_photos', models.TextField(blank=True, null=True, verbose_name='Фотографии')),
            ],
        ),
    ]
