# Generated by Django 5.2 on 2025-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Компания')),
                ('average_rating', models.TextField(blank=True, null=True, verbose_name='Средний рейтинг')),
                ('reviews_count', models.TextField(blank=True, null=True, verbose_name='Кол-во отзывов')),
            ],
        ),
    ]
